### PR TITLE
dossier : Fix/Update : Update to use Dossier via Infoblox BloxOne Platform

### PR DESCRIPTION
**Pull request by ccmarris**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x ] Verify all checks are passing.
- [x ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x ] Do NOT submit updates to dependencies unless it fixes an issue.
- [x ] Limit your pull request to one application and submit multiple pull requests if necessary.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

- The Infoblox ActiveTrust Platform has been replaced by the Infoblox BloxOne Platform (csp.infoblox.com). Users need to migrate to the new platform to continue to use Dossier. This fix/update migrates the phantom dossier integration to the new platform to ensure users are able to continue to utilize this integration. 
- i.e Migration from ActiveTrust to Bloxone (csp.infoblox.com)
- Note: Users will need a new API key.
- I have incorporated the changes to loop through the results and locally tested on v5.0.1.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

- App currently uses the ActiveTrust Platform that is being decommissioned.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

- The app will now utilize the Infoblox BloxOne platform as its endpoint for the Dossier API calls. There are no functional changes to the API itself or the functionality provided by the script.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

- Users will need to get a new API key from the BloxOne Platform - ActiveTrust Platform API will not be valid.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by ccmarris** [comment]
Sorry looks like there was a load of changes that I should have picked up before my PR. 

The key change is the base_url is missing a path element:
`base_url = "https://csp.infoblox.com/tide/api/services/intel/lookup"`

Should I close this, merge at my end and resubmit?

**Comment by gusdadiya-crest** [comment]
Hii @ccmarris 
You do not need to create new PR you can take a pull from the "next" branch then do your changes and push the code.

We suggest you convert this application to python version 3 if you have valid asset credentials with you. We strongly suggest using python 3 since python 2 support will be dropped in the near future.

Please refer to [Convert apps from Python 2 to Python 3.](https://docs.splunk.com/Documentation/Phantom/4.10.7/DevelopApps/Python3)

Thanks

**Comment by ccmarris** [comment]
Any idea when you can publish with the fix for the URL? 

Thanks

Chris

**Comment by arathore-crest** [comment]
> Any idea when you can publish with the fix for the URL?

We'll try to release the app by end of this week.

Thanks,
Aarav

**Review by tonyc-phantom — APPROVED** [review]

**Review by paulnawat — APPROVED** [review]

**Pull request merged**
